version: '3.7'
services:

  pluton_postgres:
    container_name: pluton_postgres
    hostname: pluton_postgres
    image: postgres
    environment:
      POSTGRES_DB: pultondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - pluton_postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@siberius.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
    
volumes:
  postgres:
    pgadmin: