version: '3.7'
services:

  pluton_app:
    container_name: pluton_app
    hostname: pluton_app
    image: aymenmehri/pluton:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pluton_postgres:5432/pluton
      SPRING_DATASOURCE_USER: postgres
      SPRING_DATASOURCE_PASSWORD: changeme
    ports:
      - 8080:8080
    restart: unless-stopped
    